// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQOSlB_f6wHAI9L-tm_SVjHw52t7QNPPE',
    appId: '1:41219509306:web:67a12b508649f2decfb903',
    messagingSenderId: '41219509306',
    projectId: 'firebaza-eede1',
    authDomain: 'firebaza-eede1.firebaseapp.com',
    storageBucket: 'firebaza-eede1.appspot.com',
    measurementId: 'G-WME9KFPVE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmv2MQepsqI9bq2Ibhd02GXto6UyTQ40',
    appId: '1:41219509306:android:589c943a971755d6cfb903',
    messagingSenderId: '41219509306',
    projectId: 'firebaza-eede1',
    storageBucket: 'firebaza-eede1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutTMAQ3DObiGU9mimqQurQqsfJvAudwU',
    appId: '1:41219509306:ios:6ed4b8a9d93eed41cfb903',
    messagingSenderId: '41219509306',
    projectId: 'firebaza-eede1',
    storageBucket: 'firebaza-eede1.appspot.com',
    iosClientId: '41219509306-9sbbn1a329cri17qkl1laflp14kem06r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutTMAQ3DObiGU9mimqQurQqsfJvAudwU',
    appId: '1:41219509306:ios:6ed4b8a9d93eed41cfb903',
    messagingSenderId: '41219509306',
    projectId: 'firebaza-eede1',
    storageBucket: 'firebaza-eede1.appspot.com',
    iosClientId: '41219509306-9sbbn1a329cri17qkl1laflp14kem06r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaza',
  );
}
